#pragma once

enum credentialsStatus {
	WRONG_PASSWORD,
	RIGHT_PASSWORD,
	USER_ALREADY_EXISTS,
	SUCCESSFUL_REGISTRATION,
	AUTHORIZATION_SUCCEEDED,
	AUTHORIZATION_FAILED,
	ERROR_
};

enum requestType {
	REGISTRATION,
	LOGIN
};